# Generated by Django 2.2.7 on 2019-12-27 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('apply_name', models.CharField(max_length=50)),
                ('tel_number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('money', models.CharField(max_length=30)),
                ('use_for', models.CharField(max_length=100)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
