# Generated by Django 2.2.7 on 2019-12-29 07:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('longhaotianhua', '0002_auto_20191229_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultpost',
            old_name='company_name',
            new_name='consult_company_name',
        ),
        migrations.AlterField(
            model_name='consultpost',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consult_company_name', to='longhaotianhua.IndustryColumn'),
        ),
        migrations.CreateModel(
            name='MeasurePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_company_name', models.CharField(max_length=50)),
                ('register_place', models.CharField(max_length=50)),
                ('income', models.CharField(max_length=50)),
                ('profit', models.CharField(max_length=50)),
                ('security_nums', models.CharField(max_length=50)),
                ('debt', models.CharField(max_length=50)),
                ('patent', models.CharField(max_length=50)),
                ('practice', models.CharField(max_length=50)),
                ('software', models.CharField(max_length=50)),
                ('design', models.CharField(max_length=50)),
                ('company_value', models.CharField(max_length=50)),
                ('personal_value', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measure_company_name', to='longhaotianhua.IndustryColumn')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
