# Generated by Django 2.2.7 on 2019-12-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longhaotianhua', '0003_auto_20191229_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurepost',
            name='limit',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
