# Generated by Django 2.2.7 on 2019-12-30 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('longhaotianhua', '0004_measurepost_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultpost',
            old_name='column',
            new_name='consult_column',
        ),
        migrations.RenameField(
            model_name='measurepost',
            old_name='column',
            new_name='measure_column',
        ),
    ]
