# Generated by Django 2.2.7 on 2019-12-30 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('longhaotianhua', '0005_auto_20191230_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurepost',
            name='company_value',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='measurepost',
            name='personal_value',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
